// Package apicontract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apicontract

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// Defines values for ModelListObject.
const (
	List ModelListObject = "list"
)

// Valid indicates whether the value is a known member of the ModelListObject enum.
func (e ModelListObject) Valid() bool {
	switch e {
	case List:
		return true
	default:
		return false
	}
}

// CPUInfo defines model for CPUInfo.
type CPUInfo struct {
	Cores       *int       `json:"cores,omitempty"`
	LoadAvg1    *float32   `json:"load_avg1,omitempty"`
	LoadAvg15   *float32   `json:"load_avg15,omitempty"`
	LoadAvg5    *float32   `json:"load_avg5,omitempty"`
	UtilAvgPct  *float32   `json:"util_avg_pct,omitempty"`
	UtilPerCore *[]float32 `json:"util_per_core,omitempty"`
}

// Capabilities defines model for Capabilities.
type Capabilities struct {
	Features []string `json:"features"`
	Version  int      `json:"version"`
}

// GPUSnapshot defines model for GPUSnapshot.
type GPUSnapshot struct {
	Id             *int     `json:"id,omitempty"`
	Name           *string  `json:"name,omitempty"`
	PowerDrawW     *float32 `json:"power_draw_w,omitempty"`
	TempC          *int     `json:"temp_c,omitempty"`
	UtilizationPct *float32 `json:"utilization_pct,omitempty"`
	VramFreeMb     *int     `json:"vram_free_mb,omitempty"`
	VramTotalMb    *int     `json:"vram_total_mb,omitempty"`
	VramUsedMb     *int     `json:"vram_used_mb,omitempty"`
}

// MemoryInfo defines model for MemoryInfo.
type MemoryInfo struct {
	FreeMb    *int     `json:"free_mb,omitempty"`
	LoadAvg1  *float32 `json:"load_avg1,omitempty"`
	LoadAvg15 *float32 `json:"load_avg15,omitempty"`
	LoadAvg5  *float32 `json:"load_avg5,omitempty"`
	SwapTotal *int     `json:"swap_total,omitempty"`
	SwapUsed  *int     `json:"swap_used,omitempty"`
	TotalMb   *int     `json:"total_mb,omitempty"`
	Type      *string  `json:"type,omitempty"`
	UsedMb    *int     `json:"used_mb,omitempty"`
}

// Model defines model for Model.
type Model struct {
	ContextLength   *int    `json:"context_length,omitempty"`
	Created         *int    `json:"created,omitempty"`
	Description     *string `json:"description,omitempty"`
	Id              string  `json:"id"`
	Loaded          *bool   `json:"loaded,omitempty"`
	MaxOutputTokens *int    `json:"max_output_tokens,omitempty"`
	Name            *string `json:"name,omitempty"`
	Object          string  `json:"object"`
	OwnedBy         *string `json:"owned_by,omitempty"`
	State           *string `json:"state,omitempty"`
}

// ModelList defines model for ModelList.
type ModelList struct {
	Data   []Model         `json:"data"`
	Object ModelListObject `json:"object"`
}

// ModelListObject defines model for ModelList.Object.
type ModelListObject string

// ResourceSnapshot defines model for ResourceSnapshot.
type ResourceSnapshot struct {
	Cpu     *CPUInfo       `json:"cpu,omitempty"`
	Gpus    *[]GPUSnapshot `json:"gpus,omitempty"`
	Memory  *MemoryInfo    `json:"memory,omitempty"`
	Storage *StorageInfo   `json:"storage,omitempty"`
	Vram    *VRAMInfo      `json:"vram,omitempty"`
}

// StorageInfo defines model for StorageInfo.
type StorageInfo struct {
	AvailableBytes *int    `json:"available_bytes,omitempty"`
	ModelsDir      *string `json:"models_dir,omitempty"`
	TotalBytes     *int    `json:"total_bytes,omitempty"`
	UsedBytes      *int    `json:"used_bytes,omitempty"`
}

// VRAMInfo defines model for VRAMInfo.
type VRAMInfo struct {
	FreeMb  *int `json:"free_mb,omitempty"`
	TotalMb *int `json:"total_mb,omitempty"`
	UsedMb  *int `json:"used_mb,omitempty"`
}

// VersionInfo defines model for VersionInfo.
type VersionInfo struct {
	BuildDate     string                 `json:"build_date"`
	BuildFeatures *[]string              `json:"build_features,omitempty"`
	Commit        string                 `json:"commit"`
	LlamaCppBuild *string                `json:"llama_cpp_build,omitempty"`
	LlamaCppDate  *string                `json:"llama_cpp_date,omitempty"`
	LlamaCppGit   *string                `json:"llama_cpp_git,omitempty"`
	Metal         *bool                  `json:"metal,omitempty"`
	Platform      *string                `json:"platform,omitempty"`
	RocmVersion   *string                `json:"rocm_version,omitempty"`
	Runtime       map[string]interface{} `json:"runtime"`
	Version       string                 `json:"version"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetHardware request
	GetHardware(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSystemCapabilities request
	GetSystemCapabilities(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSystemVersion request
	GetSystemVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListModels request
	ListModels(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetHardware(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHardwareRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSystemCapabilities(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSystemCapabilitiesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSystemVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSystemVersionRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListModels(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListModelsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetHardwareRequest generates requests for GetHardware
func NewGetHardwareRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/hardware")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSystemCapabilitiesRequest generates requests for GetSystemCapabilities
func NewGetSystemCapabilitiesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/system/capabilities")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSystemVersionRequest generates requests for GetSystemVersion
func NewGetSystemVersionRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/system/version")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListModelsRequest generates requests for ListModels
func NewListModelsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/models")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetHardwareWithResponse request
	GetHardwareWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHardwareResponse, error)

	// GetSystemCapabilitiesWithResponse request
	GetSystemCapabilitiesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetSystemCapabilitiesResponse, error)

	// GetSystemVersionWithResponse request
	GetSystemVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetSystemVersionResponse, error)

	// ListModelsWithResponse request
	ListModelsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListModelsResponse, error)
}

type GetHardwareResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ResourceSnapshot
}

// Status returns HTTPResponse.Status
func (r GetHardwareResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHardwareResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHardwareResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetSystemCapabilitiesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Capabilities
}

// Status returns HTTPResponse.Status
func (r GetSystemCapabilitiesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSystemCapabilitiesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetSystemCapabilitiesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetSystemVersionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *VersionInfo
}

// Status returns HTTPResponse.Status
func (r GetSystemVersionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSystemVersionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetSystemVersionResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListModelsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ModelList
}

// Status returns HTTPResponse.Status
func (r ListModelsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListModelsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListModelsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetHardwareWithResponse request returning *GetHardwareResponse
func (c *ClientWithResponses) GetHardwareWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHardwareResponse, error) {
	rsp, err := c.GetHardware(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHardwareResponse(rsp)
}

// GetSystemCapabilitiesWithResponse request returning *GetSystemCapabilitiesResponse
func (c *ClientWithResponses) GetSystemCapabilitiesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetSystemCapabilitiesResponse, error) {
	rsp, err := c.GetSystemCapabilities(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSystemCapabilitiesResponse(rsp)
}

// GetSystemVersionWithResponse request returning *GetSystemVersionResponse
func (c *ClientWithResponses) GetSystemVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetSystemVersionResponse, error) {
	rsp, err := c.GetSystemVersion(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSystemVersionResponse(rsp)
}

// ListModelsWithResponse request returning *ListModelsResponse
func (c *ClientWithResponses) ListModelsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListModelsResponse, error) {
	rsp, err := c.ListModels(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListModelsResponse(rsp)
}

// ParseGetHardwareResponse parses an HTTP response from a GetHardwareWithResponse call
func ParseGetHardwareResponse(rsp *http.Response) (*GetHardwareResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHardwareResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ResourceSnapshot
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetSystemCapabilitiesResponse parses an HTTP response from a GetSystemCapabilitiesWithResponse call
func ParseGetSystemCapabilitiesResponse(rsp *http.Response) (*GetSystemCapabilitiesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSystemCapabilitiesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Capabilities
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetSystemVersionResponse parses an HTTP response from a GetSystemVersionWithResponse call
func ParseGetSystemVersionResponse(rsp *http.Response) (*GetSystemVersionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSystemVersionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VersionInfo
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListModelsResponse parses an HTTP response from a ListModelsWithResponse call
func ParseListModelsResponse(rsp *http.Response) (*ListModelsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListModelsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ModelList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
