// Package apicontract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apicontract

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ConfigModelPatchRequestBackend.
const (
	ConfigModelPatchRequestBackendLlamacpp ConfigModelPatchRequestBackend = "llamacpp"
	ConfigModelPatchRequestBackendMlx      ConfigModelPatchRequestBackend = "mlx"
	ConfigModelPatchRequestBackendVllm     ConfigModelPatchRequestBackend = "vllm"
)

// Valid indicates whether the value is a known member of the ConfigModelPatchRequestBackend enum.
func (e ConfigModelPatchRequestBackend) Valid() bool {
	switch e {
	case ConfigModelPatchRequestBackendLlamacpp:
		return true
	case ConfigModelPatchRequestBackendMlx:
		return true
	case ConfigModelPatchRequestBackendVllm:
		return true
	default:
		return false
	}
}

// Defines values for ConfigModelRequestBackend.
const (
	ConfigModelRequestBackendLlamacpp ConfigModelRequestBackend = "llamacpp"
	ConfigModelRequestBackendMlx      ConfigModelRequestBackend = "mlx"
	ConfigModelRequestBackendVllm     ConfigModelRequestBackend = "vllm"
)

// Valid indicates whether the value is a known member of the ConfigModelRequestBackend enum.
func (e ConfigModelRequestBackend) Valid() bool {
	switch e {
	case ConfigModelRequestBackendLlamacpp:
		return true
	case ConfigModelRequestBackendMlx:
		return true
	case ConfigModelRequestBackendVllm:
		return true
	default:
		return false
	}
}

// Defines values for ModelBackend.
const (
	ModelBackendLlamacpp ModelBackend = "llamacpp"
	ModelBackendMlx      ModelBackend = "mlx"
	ModelBackendVllm     ModelBackend = "vllm"
)

// Valid indicates whether the value is a known member of the ModelBackend enum.
func (e ModelBackend) Valid() bool {
	switch e {
	case ModelBackendLlamacpp:
		return true
	case ModelBackendMlx:
		return true
	case ModelBackendVllm:
		return true
	default:
		return false
	}
}

// Defines values for ModelFitBackend.
const (
	ModelFitBackendLlamacpp ModelFitBackend = "llamacpp"
	ModelFitBackendMlx      ModelFitBackend = "mlx"
	ModelFitBackendVllm     ModelFitBackend = "vllm"
)

// Valid indicates whether the value is a known member of the ModelFitBackend enum.
func (e ModelFitBackend) Valid() bool {
	switch e {
	case ModelFitBackendLlamacpp:
		return true
	case ModelFitBackendMlx:
		return true
	case ModelFitBackendVllm:
		return true
	default:
		return false
	}
}

// Defines values for ModelFitFitLevel.
const (
	Good     ModelFitFitLevel = "good"
	Marginal ModelFitFitLevel = "marginal"
	No       ModelFitFitLevel = "no"
	Perfect  ModelFitFitLevel = "perfect"
	Tight    ModelFitFitLevel = "tight"
)

// Valid indicates whether the value is a known member of the ModelFitFitLevel enum.
func (e ModelFitFitLevel) Valid() bool {
	switch e {
	case Good:
		return true
	case Marginal:
		return true
	case No:
		return true
	case Perfect:
		return true
	case Tight:
		return true
	default:
		return false
	}
}

// Defines values for ModelFitRunMode.
const (
	CpuOffload     ModelFitRunMode = "cpu_offload"
	CpuOnly        ModelFitRunMode = "cpu_only"
	Gpu            ModelFitRunMode = "gpu"
	MoeOffload     ModelFitRunMode = "moe_offload"
	TensorParallel ModelFitRunMode = "tensor_parallel"
)

// Valid indicates whether the value is a known member of the ModelFitRunMode enum.
func (e ModelFitRunMode) Valid() bool {
	switch e {
	case CpuOffload:
		return true
	case CpuOnly:
		return true
	case Gpu:
		return true
	case MoeOffload:
		return true
	case TensorParallel:
		return true
	default:
		return false
	}
}

// Defines values for ModelListObject.
const (
	List ModelListObject = "list"
)

// Valid indicates whether the value is a known member of the ModelListObject enum.
func (e ModelListObject) Valid() bool {
	switch e {
	case List:
		return true
	default:
		return false
	}
}

// Defines values for OffloadRecommendationBackend.
const (
	Llamacpp OffloadRecommendationBackend = "llamacpp"
	Mlx      OffloadRecommendationBackend = "mlx"
	Vllm     OffloadRecommendationBackend = "vllm"
)

// Valid indicates whether the value is a known member of the OffloadRecommendationBackend enum.
func (e OffloadRecommendationBackend) Valid() bool {
	switch e {
	case Llamacpp:
		return true
	case Mlx:
		return true
	case Vllm:
		return true
	default:
		return false
	}
}

// CPUInfo defines model for CPUInfo.
type CPUInfo struct {
	Cores       *int       `json:"cores,omitempty"`
	LoadAvg1    *float32   `json:"load_avg1,omitempty"`
	LoadAvg15   *float32   `json:"load_avg15,omitempty"`
	LoadAvg5    *float32   `json:"load_avg5,omitempty"`
	UtilAvgPct  *float32   `json:"util_avg_pct,omitempty"`
	UtilPerCore *[]float32 `json:"util_per_core,omitempty"`
}

// Capabilities defines model for Capabilities.
type Capabilities struct {
	Features []string `json:"features"`
	Version  int      `json:"version"`
}

// ConfigDefaultModelRequest defines model for ConfigDefaultModelRequest.
type ConfigDefaultModelRequest struct {
	// Model Model ID or alias to use when a request omits the 'model' field.
	Model string `json:"model"`
}

// ConfigDefaultModelResponse defines model for ConfigDefaultModelResponse.
type ConfigDefaultModelResponse struct {
	// Model Configured default model ID, or null when no default is set.
	Model *string `json:"model"`
}

// ConfigGroupPatchRequest defines model for ConfigGroupPatchRequest.
type ConfigGroupPatchRequest struct {
	AutoUnload *bool `json:"autoUnload,omitempty"`
	Exclusive  *bool `json:"exclusive,omitempty"`
	Swap       *bool `json:"swap,omitempty"`
}

// ConfigInfoResponse defines model for ConfigInfoResponse.
type ConfigInfoResponse struct {
	ConfigFile string `json:"config_file"`

	// DefaultModel Configured default model ID; omitted when no default is set.
	DefaultModel *string           `json:"default_model,omitempty"`
	ModelCount   int               `json:"model_count"`
	Models       []ConfigModelInfo `json:"models"`
	ModelsDir    string            `json:"models_dir"`
}

// ConfigModelDetail Full stored config for a model plus llama-server flags parsed out of its command. ctx_size and n_gpu_layers are the raw flag values (strings); offload fields reflect the current command.
type ConfigModelDetail struct {
	Aliases          *[]string `json:"aliases,omitempty"`
	CacheTypeK       *string   `json:"cache_type_k,omitempty"`
	CacheTypeV       *string   `json:"cache_type_v,omitempty"`
	Cmd              string    `json:"cmd"`
	ConcurrencyLimit *int      `json:"concurrencyLimit,omitempty"`
	CpuMoe           *bool     `json:"cpu_moe,omitempty"`
	CpuOffloadGb     *int      `json:"cpu_offload_gb,omitempty"`
	CtxSize          *string   `json:"ctx_size,omitempty"`
	Description      *string   `json:"description,omitempty"`

	// Flags All --flags parsed from the command, as raw string values.
	Flags          *map[string]string `json:"flags,omitempty"`
	Id             string             `json:"id"`
	NCpuMoe        *int               `json:"n_cpu_moe,omitempty"`
	NGpuLayers     *string            `json:"n_gpu_layers,omitempty"`
	Name           *string            `json:"name,omitempty"`
	OverrideTensor *string            `json:"override_tensor,omitempty"`
	Ttl            *int               `json:"ttl,omitempty"`
}

// ConfigModelInfo defines model for ConfigModelInfo.
type ConfigModelInfo struct {
	FileExists *bool   `json:"file_exists,omitempty"`
	FilePath   *string `json:"file_path,omitempty"`
	Id         string  `json:"id"`
}

// ConfigModelPatchRequest defines model for ConfigModelPatchRequest.
type ConfigModelPatchRequest struct {
	Aliases *[]string `json:"aliases,omitempty"`

	// Backend Inference backend type. Controls backend-specific behaviours (e.g. slot cancellation is llamacpp-only). mlx targets Apple Silicon; vllm targets NVIDIA (CUDA); AMD ROCm requires building vllm from source. Default: llamacpp.
	Backend               *ConfigModelPatchRequestBackend `json:"backend,omitempty"`
	CacheTypeKDash        *string                         `json:"cache-type-k,omitempty"`
	CacheTypeVDash        *string                         `json:"cache-type-v,omitempty"`
	CacheTypeK            *string                         `json:"cache_type_k,omitempty"`
	CacheTypeV            *string                         `json:"cache_type_v,omitempty"`
	Cmd                   *string                         `json:"cmd,omitempty"`
	ConcurrencyLimitCamel *int                            `json:"concurrencyLimit,omitempty"`
	ConcurrencyLimit      *int                            `json:"concurrency_limit,omitempty"`
	CpuOffloadGBDash      *int                            `json:"cpu-offload-gb,omitempty"`

	// CpuMoe Offload ALL MoE expert tensors to CPU/RAM (llama.cpp --cpu-moe). false removes the flag. llamacpp only.
	CpuMoe *bool `json:"cpu_moe,omitempty"`

	// CpuOffloadGb GiB of weights to offload to CPU per GPU (vLLM --cpu-offload-gb). 0 removes the flag. vllm only.
	CpuOffloadGb   *int                    `json:"cpu_offload_gb,omitempty"`
	CtxSizeDash    *int                    `json:"ctx-size,omitempty"`
	CtxSize        *int                    `json:"ctx_size,omitempty"`
	Description    *string                 `json:"description,omitempty"`
	Flags          *map[string]interface{} `json:"flags,omitempty"`
	NCpuMoeDash    *int                    `json:"n-cpu-moe,omitempty"`
	NGPULayersDash *int                    `json:"n-gpu-layers,omitempty"`

	// NCpuMoe Number of leading layers whose MoE expert tensors are offloaded to CPU/RAM (llama.cpp --n-cpu-moe). 0 removes the flag. llamacpp only.
	NCpuMoe            *int    `json:"n_cpu_moe,omitempty"`
	NGpuLayers         *int    `json:"n_gpu_layers,omitempty"`
	Name               *string `json:"name,omitempty"`
	OverrideTensorDash *string `json:"override-tensor,omitempty"`

	// OverrideTensor Advanced tensor placement override regex (llama.cpp --override-tensor). Empty removes the flag. llamacpp only.
	OverrideTensor *string `json:"override_tensor,omitempty"`
	Ttl            *int    `json:"ttl,omitempty"`
}

// ConfigModelPatchRequestBackend Inference backend type. Controls backend-specific behaviours (e.g. slot cancellation is llamacpp-only). mlx targets Apple Silicon; vllm targets NVIDIA (CUDA); AMD ROCm requires building vllm from source. Default: llamacpp.
type ConfigModelPatchRequestBackend string

// ConfigModelRequest defines model for ConfigModelRequest.
type ConfigModelRequest struct {
	Aliases *[]string `json:"aliases,omitempty"`

	// Backend Inference backend type. Controls backend-specific behaviours (e.g. slot cancellation is llamacpp-only). mlx targets Apple Silicon; vllm targets NVIDIA (CUDA); AMD ROCm requires building vllm from source. Default: llamacpp.
	Backend *ConfigModelRequestBackend `json:"backend,omitempty"`
	Cmd     string                     `json:"cmd"`

	// CpuMoe Offload ALL MoE expert tensors to CPU/RAM (llama.cpp --cpu-moe). llamacpp only.
	CpuMoe *bool `json:"cpu_moe,omitempty"`

	// CpuOffloadGb GiB of weights to offload to CPU per GPU (vLLM --cpu-offload-gb). vllm only.
	CpuOffloadGb *int    `json:"cpu_offload_gb,omitempty"`
	Description  *string `json:"description,omitempty"`
	Id           string  `json:"id"`

	// NCpuMoe Number of leading layers whose MoE expert tensors are offloaded to CPU/RAM (llama.cpp --n-cpu-moe). llamacpp only.
	NCpuMoe *int    `json:"n_cpu_moe,omitempty"`
	Name    *string `json:"name,omitempty"`

	// OverrideTensor Advanced tensor placement override regex (llama.cpp --override-tensor). llamacpp only.
	OverrideTensor *string `json:"override_tensor,omitempty"`
	Ttl            *int    `json:"ttl,omitempty"`
}

// ConfigModelRequestBackend Inference backend type. Controls backend-specific behaviours (e.g. slot cancellation is llamacpp-only). mlx targets Apple Silicon; vllm targets NVIDIA (CUDA); AMD ROCm requires building vllm from source. Default: llamacpp.
type ConfigModelRequestBackend string

// ConfigModelResponse defines model for ConfigModelResponse.
type ConfigModelResponse struct {
	Id     string `json:"id"`
	Status string `json:"status"`

	// Warnings Non-fatal warnings produced while applying the request, e.g. offload knobs unsupported by the model's backend. Omitted when there are none.
	Warnings *[]string `json:"warnings,omitempty"`
}

// FitReport Fit of every configured model to this host. Aggregated by skein across providers for fleet placement.
type FitReport struct {
	// Models Per-model fit results.
	Models []ModelFit `json:"models"`

	// VramFreeMb Currently free VRAM (MB).
	VramFreeMb *int `json:"vram_free_mb,omitempty"`

	// VramTotalMb Total VRAM/unified pool (MB).
	VramTotalMb *int `json:"vram_total_mb,omitempty"`
}

// FitScore Per-dimension fit scores in [0,1], weighted by use-case (ported from llmfit fit.rs ScoreComponents).
type FitScore struct {
	// Context Context-capacity score: usable context vs the model's trained max.
	Context *float32 `json:"context,omitempty"`

	// Fit Memory-headroom score: how comfortably the model fits.
	Fit *float32 `json:"fit,omitempty"`

	// Overall Weighted overall score.
	Overall *float32 `json:"overall,omitempty"`

	// Quality Model quality score (benchmark-derived).
	Quality *float32 `json:"quality,omitempty"`

	// Speed Speed score from estimated tokens/sec on this host.
	Speed *float32 `json:"speed,omitempty"`
}

// GPUSnapshot defines model for GPUSnapshot.
type GPUSnapshot struct {
	Id             *int     `json:"id,omitempty"`
	Name           *string  `json:"name,omitempty"`
	PowerDrawW     *float32 `json:"power_draw_w,omitempty"`
	TempC          *int     `json:"temp_c,omitempty"`
	UtilizationPct *float32 `json:"utilization_pct,omitempty"`
	VramFreeMb     *int     `json:"vram_free_mb,omitempty"`
	VramTotalMb    *int     `json:"vram_total_mb,omitempty"`
	VramUsedMb     *int     `json:"vram_used_mb,omitempty"`
}

// LoadedModelInfo defines model for LoadedModelInfo.
type LoadedModelInfo struct {
	// Id Model ID as defined in config.
	Id *string `json:"id,omitempty"`

	// KvEstimateMb Estimated KV cache MB: max(0, vram.used_mb - model_mb).
	KvEstimateMb *int `json:"kv_estimate_mb,omitempty"`

	// ModelMb Model weight file size in MB (disk proxy for VRAM used by weights).
	ModelMb *int `json:"model_mb,omitempty"`
}

// MemoryInfo defines model for MemoryInfo.
type MemoryInfo struct {
	FreeMb    *int     `json:"free_mb,omitempty"`
	LoadAvg1  *float32 `json:"load_avg1,omitempty"`
	LoadAvg15 *float32 `json:"load_avg15,omitempty"`
	LoadAvg5  *float32 `json:"load_avg5,omitempty"`
	SwapTotal *int     `json:"swap_total,omitempty"`
	SwapUsed  *int     `json:"swap_used,omitempty"`
	TotalMb   *int     `json:"total_mb,omitempty"`
	Type      *string  `json:"type,omitempty"`
	UsedMb    *int     `json:"used_mb,omitempty"`
}

// Model defines model for Model.
type Model struct {
	// Backend Inference backend type.
	Backend       *ModelBackend `json:"backend,omitempty"`
	ContextLength *int          `json:"context_length,omitempty"`

	// CpuMoe True when --cpu-moe is present in the model command (all MoE experts offloaded to CPU).
	CpuMoe *bool `json:"cpu_moe,omitempty"`

	// CpuOffloadGb Current --cpu-offload-gb value parsed from the model command, when set (vLLM weight offload).
	CpuOffloadGb *int `json:"cpu_offload_gb,omitempty"`
	Created      *int `json:"created,omitempty"`

	// Default True when this model is the configured default, used for requests that omit the 'model' field. Listed first in the model list. llama-skein extension to the OpenAI schema.
	Default         *bool   `json:"default,omitempty"`
	Description     *string `json:"description,omitempty"`
	Id              string  `json:"id"`
	Loaded          *bool   `json:"loaded,omitempty"`
	MaxOutputTokens *int    `json:"max_output_tokens,omitempty"`

	// NCpuMoe Current --n-cpu-moe value parsed from the model command, when set (llama.cpp MoE expert CPU offload).
	NCpuMoe *int    `json:"n_cpu_moe,omitempty"`
	Name    *string `json:"name,omitempty"`
	Object  string  `json:"object"`

	// OverrideTensor Current --override-tensor value parsed from the model command, when set (llama.cpp tensor placement).
	OverrideTensor *string `json:"override_tensor,omitempty"`
	OwnedBy        *string `json:"owned_by,omitempty"`
	State          *string `json:"state,omitempty"`
}

// ModelBackend Inference backend type.
type ModelBackend string

// ModelFit Fit of one model to THIS host: whether it runs, how well, and the max SAFE context (output- and overhead-reserved). Ported from llmfit fit.rs ModelFit.
type ModelFit struct {
	// Backend Inference backend.
	Backend ModelFitBackend `json:"backend"`

	// ConfiguredCtx Current --ctx-size in the model command (the KV allocation / hard n_ctx).
	ConfiguredCtx *int `json:"configured_ctx,omitempty"`

	// EstTokensPerSec Estimated generation throughput on this host (benchmark-derived).
	EstTokensPerSec *float32 `json:"est_tokens_per_sec,omitempty"`

	// FitLevel How well the model fits this host.
	FitLevel ModelFitFitLevel `json:"fit_level"`

	// KvMbAtMaxSafeCtx KV-cache size (MB) at max_safe_ctx, given the host's cache-type quantization.
	KvMbAtMaxSafeCtx *int `json:"kv_mb_at_max_safe_ctx,omitempty"`

	// MaxSafeCtx Max context callers should fill: reserves the output budget plus compute/overhead so prompt+generation never exceed the backend's hard n_ctx. THIS is the number opencode/skein should trim to, not configured_ctx.
	MaxSafeCtx int `json:"max_safe_ctx"`

	// Model Model ID.
	Model string `json:"model"`

	// ModelMb Model weights resident size (MB).
	ModelMb *int `json:"model_mb,omitempty"`

	// Reason Human-readable explanation of the fit verdict.
	Reason *string `json:"reason,omitempty"`

	// RunMode How the model would run given memory.
	RunMode *ModelFitRunMode `json:"run_mode,omitempty"`

	// Score Per-dimension fit scores in [0,1], weighted by use-case (ported from llmfit fit.rs ScoreComponents).
	Score *FitScore `json:"score,omitempty"`

	// VramRequiredMb Estimated VRAM needed: weights + KV + compute buffers (MB).
	VramRequiredMb *int `json:"vram_required_mb,omitempty"`

	// VramTotalMb Total VRAM/unified memory pool (MB).
	VramTotalMb *int `json:"vram_total_mb,omitempty"`
}

// ModelFitBackend Inference backend.
type ModelFitBackend string

// ModelFitFitLevel How well the model fits this host.
type ModelFitFitLevel string

// ModelFitRunMode How the model would run given memory.
type ModelFitRunMode string

// ModelList defines model for ModelList.
type ModelList struct {
	Data   []Model         `json:"data"`
	Object ModelListObject `json:"object"`
}

// ModelListObject defines model for ModelList.Object.
type ModelListObject string

// OffloadRecommendation defines model for OffloadRecommendation.
type OffloadRecommendation struct {
	// Applicable False for non-MoE models and backends where offload does not apply (e.g. mlx); see reason.
	Applicable bool `json:"applicable"`

	// Backend Inference backend the recommendation targets.
	Backend OffloadRecommendationBackend `json:"backend"`

	// CtxSize Context length assumed for the KV-cache portion of the estimate.
	CtxSize *int `json:"ctx_size,omitempty"`

	// ExpertBytesTotal Estimated total bytes of MoE expert tensors in the model.
	ExpertBytesTotal *int `json:"expert_bytes_total,omitempty"`

	// FitsFullyOnGpu True when the model fits in free VRAM without any offload.
	FitsFullyOnGpu *bool `json:"fits_fully_on_gpu,omitempty"`

	// NCpuMoe Recommended --n-cpu-moe value (number of leading layers whose MoE experts to offload to CPU). 0 means the model fits fully on GPU.
	NCpuMoe *int `json:"n_cpu_moe,omitempty"`

	// Reason Human-readable explanation of the recommendation or why it is not applicable.
	Reason *string `json:"reason,omitempty"`

	// VramFreeMb Free VRAM (MB) used for the calculation; falls back to system RAM when no GPU is present.
	VramFreeMb *int `json:"vram_free_mb,omitempty"`
}

// OffloadRecommendationBackend Inference backend the recommendation targets.
type OffloadRecommendationBackend string

// ReloadResponse defines model for ReloadResponse.
type ReloadResponse struct {
	Status string `json:"status"`
}

// ResourceSnapshot defines model for ResourceSnapshot.
type ResourceSnapshot struct {
	Cpu         *CPUInfo         `json:"cpu,omitempty"`
	Gpus        *[]GPUSnapshot   `json:"gpus,omitempty"`
	LoadedModel *LoadedModelInfo `json:"loaded_model,omitempty"`
	Memory      *MemoryInfo      `json:"memory,omitempty"`
	Storage     *StorageInfo     `json:"storage,omitempty"`
	Vram        *VRAMInfo        `json:"vram,omitempty"`
}

// StorageInfo defines model for StorageInfo.
type StorageInfo struct {
	AvailableBytes *int    `json:"available_bytes,omitempty"`
	ModelsDir      *string `json:"models_dir,omitempty"`
	TotalBytes     *int    `json:"total_bytes,omitempty"`
	UsedBytes      *int    `json:"used_bytes,omitempty"`
}

// VRAMInfo defines model for VRAMInfo.
type VRAMInfo struct {
	FreeMb  *int `json:"free_mb,omitempty"`
	TotalMb *int `json:"total_mb,omitempty"`
	UsedMb  *int `json:"used_mb,omitempty"`
}

// VersionInfo defines model for VersionInfo.
type VersionInfo struct {
	BuildDate     string                 `json:"build_date"`
	BuildFeatures *[]string              `json:"build_features,omitempty"`
	Commit        string                 `json:"commit"`
	LlamaCppBuild *string                `json:"llama_cpp_build,omitempty"`
	LlamaCppDate  *string                `json:"llama_cpp_date,omitempty"`
	LlamaCppGit   *string                `json:"llama_cpp_git,omitempty"`
	Metal         *bool                  `json:"metal,omitempty"`
	Platform      *string                `json:"platform,omitempty"`
	RocmVersion   *string                `json:"rocm_version,omitempty"`
	Runtime       map[string]interface{} `json:"runtime"`
	Version       string                 `json:"version"`
}

// GetModelFitParams defines parameters for GetModelFit.
type GetModelFitParams struct {
	// Ctx Score this context size instead of computing max_safe_ctx.
	Ctx *int `form:"ctx,omitempty" json:"ctx,omitempty"`
}

// SetDefaultModelJSONRequestBody defines body for SetDefaultModel for application/json ContentType.
type SetDefaultModelJSONRequestBody = ConfigDefaultModelRequest

// PatchConfigGroupJSONRequestBody defines body for PatchConfigGroup for application/json ContentType.
type PatchConfigGroupJSONRequestBody = ConfigGroupPatchRequest

// AddConfigModelJSONRequestBody defines body for AddConfigModel for application/json ContentType.
type AddConfigModelJSONRequestBody = ConfigModelRequest

// PatchConfigModelJSONRequestBody defines body for PatchConfigModel for application/json ContentType.
type PatchConfigModelJSONRequestBody = ConfigModelPatchRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ClearDefaultModel request
	ClearDefaultModel(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDefaultModel request
	GetDefaultModel(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SetDefaultModelWithBody request with any body
	SetDefaultModelWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SetDefaultModel(ctx context.Context, body SetDefaultModelJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PatchConfigGroupWithBody request with any body
	PatchConfigGroupWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PatchConfigGroup(ctx context.Context, id string, body PatchConfigGroupJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetConfigInfo request
	GetConfigInfo(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AddConfigModelWithBody request with any body
	AddConfigModelWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AddConfigModel(ctx context.Context, body AddConfigModelJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RemoveConfigModel request
	RemoveConfigModel(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetConfigModel request
	GetConfigModel(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PatchConfigModelWithBody request with any body
	PatchConfigModelWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PatchConfigModel(ctx context.Context, id string, body PatchConfigModelJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReloadConfig request
	ReloadConfig(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetFitReport request
	GetFitReport(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetModelFit request
	GetModelFit(ctx context.Context, model string, params *GetModelFitParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHardware request
	GetHardware(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetOffloadRecommendation request
	GetOffloadRecommendation(ctx context.Context, model string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSystemCapabilities request
	GetSystemCapabilities(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSystemVersion request
	GetSystemVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListModels request
	ListModels(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ClearDefaultModel(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewClearDefaultModelRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDefaultModel(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDefaultModelRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SetDefaultModelWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetDefaultModelRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SetDefaultModel(ctx context.Context, body SetDefaultModelJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetDefaultModelRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchConfigGroupWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchConfigGroupRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchConfigGroup(ctx context.Context, id string, body PatchConfigGroupJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchConfigGroupRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetConfigInfo(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetConfigInfoRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddConfigModelWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddConfigModelRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddConfigModel(ctx context.Context, body AddConfigModelJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddConfigModelRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RemoveConfigModel(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRemoveConfigModelRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetConfigModel(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetConfigModelRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchConfigModelWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchConfigModelRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchConfigModel(ctx context.Context, id string, body PatchConfigModelJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchConfigModelRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReloadConfig(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReloadConfigRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetFitReport(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetFitReportRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetModelFit(ctx context.Context, model string, params *GetModelFitParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetModelFitRequest(c.Server, model, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHardware(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHardwareRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetOffloadRecommendation(ctx context.Context, model string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetOffloadRecommendationRequest(c.Server, model)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSystemCapabilities(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSystemCapabilitiesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSystemVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSystemVersionRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListModels(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListModelsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewClearDefaultModelRequest generates requests for ClearDefaultModel
func NewClearDefaultModelRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/config/default-model")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDefaultModelRequest generates requests for GetDefaultModel
func NewGetDefaultModelRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/config/default-model")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSetDefaultModelRequest calls the generic SetDefaultModel builder with application/json body
func NewSetDefaultModelRequest(server string, body SetDefaultModelJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSetDefaultModelRequestWithBody(server, "application/json", bodyReader)
}

// NewSetDefaultModelRequestWithBody generates requests for SetDefaultModel with any type of body
func NewSetDefaultModelRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/config/default-model")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPatchConfigGroupRequest calls the generic PatchConfigGroup builder with application/json body
func NewPatchConfigGroupRequest(server string, id string, body PatchConfigGroupJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchConfigGroupRequestWithBody(server, id, "application/json", bodyReader)
}

// NewPatchConfigGroupRequestWithBody generates requests for PatchConfigGroup with any type of body
func NewPatchConfigGroupRequestWithBody(server string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/config/groups/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPatch, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetConfigInfoRequest generates requests for GetConfigInfo
func NewGetConfigInfoRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/config/info")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAddConfigModelRequest calls the generic AddConfigModel builder with application/json body
func NewAddConfigModelRequest(server string, body AddConfigModelJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAddConfigModelRequestWithBody(server, "application/json", bodyReader)
}

// NewAddConfigModelRequestWithBody generates requests for AddConfigModel with any type of body
func NewAddConfigModelRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/config/models")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewRemoveConfigModelRequest generates requests for RemoveConfigModel
func NewRemoveConfigModelRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/config/models/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetConfigModelRequest generates requests for GetConfigModel
func NewGetConfigModelRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/config/models/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPatchConfigModelRequest calls the generic PatchConfigModel builder with application/json body
func NewPatchConfigModelRequest(server string, id string, body PatchConfigModelJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchConfigModelRequestWithBody(server, id, "application/json", bodyReader)
}

// NewPatchConfigModelRequestWithBody generates requests for PatchConfigModel with any type of body
func NewPatchConfigModelRequestWithBody(server string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/config/models/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPatch, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewReloadConfigRequest generates requests for ReloadConfig
func NewReloadConfigRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/config/reload")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetFitReportRequest generates requests for GetFitReport
func NewGetFitReportRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/fit")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetModelFitRequest generates requests for GetModelFit
func NewGetModelFitRequest(server string, model string, params *GetModelFitParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "model", model, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/fit/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Ctx != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "ctx", *params.Ctx, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHardwareRequest generates requests for GetHardware
func NewGetHardwareRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/hardware")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetOffloadRecommendationRequest generates requests for GetOffloadRecommendation
func NewGetOffloadRecommendationRequest(server string, model string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "model", model, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/models/offload/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSystemCapabilitiesRequest generates requests for GetSystemCapabilities
func NewGetSystemCapabilitiesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/system/capabilities")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSystemVersionRequest generates requests for GetSystemVersion
func NewGetSystemVersionRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/system/version")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListModelsRequest generates requests for ListModels
func NewListModelsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/models")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ClearDefaultModelWithResponse request
	ClearDefaultModelWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ClearDefaultModelResponse, error)

	// GetDefaultModelWithResponse request
	GetDefaultModelWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetDefaultModelResponse, error)

	// SetDefaultModelWithBodyWithResponse request with any body
	SetDefaultModelWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SetDefaultModelResponse, error)

	SetDefaultModelWithResponse(ctx context.Context, body SetDefaultModelJSONRequestBody, reqEditors ...RequestEditorFn) (*SetDefaultModelResponse, error)

	// PatchConfigGroupWithBodyWithResponse request with any body
	PatchConfigGroupWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchConfigGroupResponse, error)

	PatchConfigGroupWithResponse(ctx context.Context, id string, body PatchConfigGroupJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchConfigGroupResponse, error)

	// GetConfigInfoWithResponse request
	GetConfigInfoWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetConfigInfoResponse, error)

	// AddConfigModelWithBodyWithResponse request with any body
	AddConfigModelWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddConfigModelResponse, error)

	AddConfigModelWithResponse(ctx context.Context, body AddConfigModelJSONRequestBody, reqEditors ...RequestEditorFn) (*AddConfigModelResponse, error)

	// RemoveConfigModelWithResponse request
	RemoveConfigModelWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*RemoveConfigModelResponse, error)

	// GetConfigModelWithResponse request
	GetConfigModelWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetConfigModelResponse, error)

	// PatchConfigModelWithBodyWithResponse request with any body
	PatchConfigModelWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchConfigModelResponse, error)

	PatchConfigModelWithResponse(ctx context.Context, id string, body PatchConfigModelJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchConfigModelResponse, error)

	// ReloadConfigWithResponse request
	ReloadConfigWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ReloadConfigResponse, error)

	// GetFitReportWithResponse request
	GetFitReportWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetFitReportResponse, error)

	// GetModelFitWithResponse request
	GetModelFitWithResponse(ctx context.Context, model string, params *GetModelFitParams, reqEditors ...RequestEditorFn) (*GetModelFitResponse, error)

	// GetHardwareWithResponse request
	GetHardwareWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHardwareResponse, error)

	// GetOffloadRecommendationWithResponse request
	GetOffloadRecommendationWithResponse(ctx context.Context, model string, reqEditors ...RequestEditorFn) (*GetOffloadRecommendationResponse, error)

	// GetSystemCapabilitiesWithResponse request
	GetSystemCapabilitiesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetSystemCapabilitiesResponse, error)

	// GetSystemVersionWithResponse request
	GetSystemVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetSystemVersionResponse, error)

	// ListModelsWithResponse request
	ListModelsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListModelsResponse, error)
}

type ClearDefaultModelResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *ConfigModelResponse
}

// Status returns HTTPResponse.Status
func (r ClearDefaultModelResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ClearDefaultModelResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ClearDefaultModelResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetDefaultModelResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ConfigDefaultModelResponse
}

// Status returns HTTPResponse.Status
func (r GetDefaultModelResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDefaultModelResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetDefaultModelResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type SetDefaultModelResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *ConfigModelResponse
}

// Status returns HTTPResponse.Status
func (r SetDefaultModelResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SetDefaultModelResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SetDefaultModelResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PatchConfigGroupResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *ConfigModelResponse
}

// Status returns HTTPResponse.Status
func (r PatchConfigGroupResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PatchConfigGroupResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PatchConfigGroupResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetConfigInfoResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ConfigInfoResponse
}

// Status returns HTTPResponse.Status
func (r GetConfigInfoResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetConfigInfoResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetConfigInfoResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type AddConfigModelResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *ConfigModelResponse
}

// Status returns HTTPResponse.Status
func (r AddConfigModelResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AddConfigModelResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AddConfigModelResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RemoveConfigModelResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *ConfigModelResponse
}

// Status returns HTTPResponse.Status
func (r RemoveConfigModelResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RemoveConfigModelResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RemoveConfigModelResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetConfigModelResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ConfigModelDetail
}

// Status returns HTTPResponse.Status
func (r GetConfigModelResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetConfigModelResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetConfigModelResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PatchConfigModelResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *ConfigModelResponse
}

// Status returns HTTPResponse.Status
func (r PatchConfigModelResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PatchConfigModelResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PatchConfigModelResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ReloadConfigResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *ReloadResponse
}

// Status returns HTTPResponse.Status
func (r ReloadConfigResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReloadConfigResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ReloadConfigResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetFitReportResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *FitReport
}

// Status returns HTTPResponse.Status
func (r GetFitReportResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetFitReportResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetFitReportResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetModelFitResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ModelFit
}

// Status returns HTTPResponse.Status
func (r GetModelFitResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetModelFitResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetModelFitResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetHardwareResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ResourceSnapshot
}

// Status returns HTTPResponse.Status
func (r GetHardwareResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHardwareResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHardwareResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetOffloadRecommendationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *OffloadRecommendation
}

// Status returns HTTPResponse.Status
func (r GetOffloadRecommendationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetOffloadRecommendationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetOffloadRecommendationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetSystemCapabilitiesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Capabilities
}

// Status returns HTTPResponse.Status
func (r GetSystemCapabilitiesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSystemCapabilitiesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetSystemCapabilitiesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetSystemVersionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *VersionInfo
}

// Status returns HTTPResponse.Status
func (r GetSystemVersionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSystemVersionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetSystemVersionResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListModelsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ModelList
}

// Status returns HTTPResponse.Status
func (r ListModelsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListModelsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListModelsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ClearDefaultModelWithResponse request returning *ClearDefaultModelResponse
func (c *ClientWithResponses) ClearDefaultModelWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ClearDefaultModelResponse, error) {
	rsp, err := c.ClearDefaultModel(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseClearDefaultModelResponse(rsp)
}

// GetDefaultModelWithResponse request returning *GetDefaultModelResponse
func (c *ClientWithResponses) GetDefaultModelWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetDefaultModelResponse, error) {
	rsp, err := c.GetDefaultModel(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDefaultModelResponse(rsp)
}

// SetDefaultModelWithBodyWithResponse request with arbitrary body returning *SetDefaultModelResponse
func (c *ClientWithResponses) SetDefaultModelWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SetDefaultModelResponse, error) {
	rsp, err := c.SetDefaultModelWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSetDefaultModelResponse(rsp)
}

func (c *ClientWithResponses) SetDefaultModelWithResponse(ctx context.Context, body SetDefaultModelJSONRequestBody, reqEditors ...RequestEditorFn) (*SetDefaultModelResponse, error) {
	rsp, err := c.SetDefaultModel(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSetDefaultModelResponse(rsp)
}

// PatchConfigGroupWithBodyWithResponse request with arbitrary body returning *PatchConfigGroupResponse
func (c *ClientWithResponses) PatchConfigGroupWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchConfigGroupResponse, error) {
	rsp, err := c.PatchConfigGroupWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchConfigGroupResponse(rsp)
}

func (c *ClientWithResponses) PatchConfigGroupWithResponse(ctx context.Context, id string, body PatchConfigGroupJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchConfigGroupResponse, error) {
	rsp, err := c.PatchConfigGroup(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchConfigGroupResponse(rsp)
}

// GetConfigInfoWithResponse request returning *GetConfigInfoResponse
func (c *ClientWithResponses) GetConfigInfoWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetConfigInfoResponse, error) {
	rsp, err := c.GetConfigInfo(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetConfigInfoResponse(rsp)
}

// AddConfigModelWithBodyWithResponse request with arbitrary body returning *AddConfigModelResponse
func (c *ClientWithResponses) AddConfigModelWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddConfigModelResponse, error) {
	rsp, err := c.AddConfigModelWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddConfigModelResponse(rsp)
}

func (c *ClientWithResponses) AddConfigModelWithResponse(ctx context.Context, body AddConfigModelJSONRequestBody, reqEditors ...RequestEditorFn) (*AddConfigModelResponse, error) {
	rsp, err := c.AddConfigModel(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddConfigModelResponse(rsp)
}

// RemoveConfigModelWithResponse request returning *RemoveConfigModelResponse
func (c *ClientWithResponses) RemoveConfigModelWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*RemoveConfigModelResponse, error) {
	rsp, err := c.RemoveConfigModel(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRemoveConfigModelResponse(rsp)
}

// GetConfigModelWithResponse request returning *GetConfigModelResponse
func (c *ClientWithResponses) GetConfigModelWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetConfigModelResponse, error) {
	rsp, err := c.GetConfigModel(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetConfigModelResponse(rsp)
}

// PatchConfigModelWithBodyWithResponse request with arbitrary body returning *PatchConfigModelResponse
func (c *ClientWithResponses) PatchConfigModelWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchConfigModelResponse, error) {
	rsp, err := c.PatchConfigModelWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchConfigModelResponse(rsp)
}

func (c *ClientWithResponses) PatchConfigModelWithResponse(ctx context.Context, id string, body PatchConfigModelJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchConfigModelResponse, error) {
	rsp, err := c.PatchConfigModel(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchConfigModelResponse(rsp)
}

// ReloadConfigWithResponse request returning *ReloadConfigResponse
func (c *ClientWithResponses) ReloadConfigWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ReloadConfigResponse, error) {
	rsp, err := c.ReloadConfig(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReloadConfigResponse(rsp)
}

// GetFitReportWithResponse request returning *GetFitReportResponse
func (c *ClientWithResponses) GetFitReportWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetFitReportResponse, error) {
	rsp, err := c.GetFitReport(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetFitReportResponse(rsp)
}

// GetModelFitWithResponse request returning *GetModelFitResponse
func (c *ClientWithResponses) GetModelFitWithResponse(ctx context.Context, model string, params *GetModelFitParams, reqEditors ...RequestEditorFn) (*GetModelFitResponse, error) {
	rsp, err := c.GetModelFit(ctx, model, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetModelFitResponse(rsp)
}

// GetHardwareWithResponse request returning *GetHardwareResponse
func (c *ClientWithResponses) GetHardwareWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHardwareResponse, error) {
	rsp, err := c.GetHardware(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHardwareResponse(rsp)
}

// GetOffloadRecommendationWithResponse request returning *GetOffloadRecommendationResponse
func (c *ClientWithResponses) GetOffloadRecommendationWithResponse(ctx context.Context, model string, reqEditors ...RequestEditorFn) (*GetOffloadRecommendationResponse, error) {
	rsp, err := c.GetOffloadRecommendation(ctx, model, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetOffloadRecommendationResponse(rsp)
}

// GetSystemCapabilitiesWithResponse request returning *GetSystemCapabilitiesResponse
func (c *ClientWithResponses) GetSystemCapabilitiesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetSystemCapabilitiesResponse, error) {
	rsp, err := c.GetSystemCapabilities(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSystemCapabilitiesResponse(rsp)
}

// GetSystemVersionWithResponse request returning *GetSystemVersionResponse
func (c *ClientWithResponses) GetSystemVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetSystemVersionResponse, error) {
	rsp, err := c.GetSystemVersion(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSystemVersionResponse(rsp)
}

// ListModelsWithResponse request returning *ListModelsResponse
func (c *ClientWithResponses) ListModelsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListModelsResponse, error) {
	rsp, err := c.ListModels(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListModelsResponse(rsp)
}

// ParseClearDefaultModelResponse parses an HTTP response from a ClearDefaultModelWithResponse call
func ParseClearDefaultModelResponse(rsp *http.Response) (*ClearDefaultModelResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ClearDefaultModelResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest ConfigModelResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	}

	return response, nil
}

// ParseGetDefaultModelResponse parses an HTTP response from a GetDefaultModelWithResponse call
func ParseGetDefaultModelResponse(rsp *http.Response) (*GetDefaultModelResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDefaultModelResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ConfigDefaultModelResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseSetDefaultModelResponse parses an HTTP response from a SetDefaultModelWithResponse call
func ParseSetDefaultModelResponse(rsp *http.Response) (*SetDefaultModelResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SetDefaultModelResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest ConfigModelResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	}

	return response, nil
}

// ParsePatchConfigGroupResponse parses an HTTP response from a PatchConfigGroupWithResponse call
func ParsePatchConfigGroupResponse(rsp *http.Response) (*PatchConfigGroupResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PatchConfigGroupResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest ConfigModelResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	}

	return response, nil
}

// ParseGetConfigInfoResponse parses an HTTP response from a GetConfigInfoWithResponse call
func ParseGetConfigInfoResponse(rsp *http.Response) (*GetConfigInfoResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetConfigInfoResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ConfigInfoResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseAddConfigModelResponse parses an HTTP response from a AddConfigModelWithResponse call
func ParseAddConfigModelResponse(rsp *http.Response) (*AddConfigModelResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AddConfigModelResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest ConfigModelResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	}

	return response, nil
}

// ParseRemoveConfigModelResponse parses an HTTP response from a RemoveConfigModelWithResponse call
func ParseRemoveConfigModelResponse(rsp *http.Response) (*RemoveConfigModelResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RemoveConfigModelResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest ConfigModelResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	}

	return response, nil
}

// ParseGetConfigModelResponse parses an HTTP response from a GetConfigModelWithResponse call
func ParseGetConfigModelResponse(rsp *http.Response) (*GetConfigModelResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetConfigModelResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ConfigModelDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePatchConfigModelResponse parses an HTTP response from a PatchConfigModelWithResponse call
func ParsePatchConfigModelResponse(rsp *http.Response) (*PatchConfigModelResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PatchConfigModelResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest ConfigModelResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	}

	return response, nil
}

// ParseReloadConfigResponse parses an HTTP response from a ReloadConfigWithResponse call
func ParseReloadConfigResponse(rsp *http.Response) (*ReloadConfigResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReloadConfigResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest ReloadResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	}

	return response, nil
}

// ParseGetFitReportResponse parses an HTTP response from a GetFitReportWithResponse call
func ParseGetFitReportResponse(rsp *http.Response) (*GetFitReportResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetFitReportResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FitReport
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetModelFitResponse parses an HTTP response from a GetModelFitWithResponse call
func ParseGetModelFitResponse(rsp *http.Response) (*GetModelFitResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetModelFitResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ModelFit
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHardwareResponse parses an HTTP response from a GetHardwareWithResponse call
func ParseGetHardwareResponse(rsp *http.Response) (*GetHardwareResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHardwareResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ResourceSnapshot
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetOffloadRecommendationResponse parses an HTTP response from a GetOffloadRecommendationWithResponse call
func ParseGetOffloadRecommendationResponse(rsp *http.Response) (*GetOffloadRecommendationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetOffloadRecommendationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest OffloadRecommendation
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetSystemCapabilitiesResponse parses an HTTP response from a GetSystemCapabilitiesWithResponse call
func ParseGetSystemCapabilitiesResponse(rsp *http.Response) (*GetSystemCapabilitiesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSystemCapabilitiesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Capabilities
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetSystemVersionResponse parses an HTTP response from a GetSystemVersionWithResponse call
func ParseGetSystemVersionResponse(rsp *http.Response) (*GetSystemVersionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSystemVersionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VersionInfo
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListModelsResponse parses an HTTP response from a ListModelsWithResponse call
func ParseListModelsResponse(rsp *http.Response) (*ListModelsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListModelsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ModelList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
